### ISSUE TITLE
Feature: Restore window state

### ISSUE THREAD

**Issue by Jack-the-Pro101** [Jack-the-Pro101/manderrow#6]
The Tauri [official plugin](https://v2.tauri.app/plugin/window-state/) for restoring window state does not provide any flexibility on what properties are saved/restored, despite providing flags of all the supported window properties.

This is an issue as the main window should not be visible on app start to allow for resource loading to complete and to prevent a strange annoyance where a blank white screen is seen briefly when starting the app. The workaround for this issue is to start the app with a splash screen window along with a hidden main window, unhiding the main window only when ready.

The Tauri plugin prevents this workaround by saving the visible state of the main window when closing the application, and automatically restoring it the next time the app starts.

This issue must be fixed.

**Comment by mpfaff** [comment]
Fixed by f799883
